### ISSUE TITLE
Add support for micronaut-data

### ISSUE THREAD

**Issue by Panthaaaa** [micronaut-projects/micronaut-reactor#11]
Based on a short gitter discussion with @graemerocher this should be the place to add an ReactorCrudRepository for micronaut-data, but I have no idea how to integrate both modules.

**Comment by graemerocher** [comment]
it should be as simple as adding `reactor-data` module subproject and then just defining an interface that exposes Reactor types

**Comment by Panthaaaa** [comment]
Ok, I'll make a PR for that.
But how will it be used by micronaut-data?

**Comment by graemerocher** [comment]
This is implemented in https://github.com/micronaut-projects/micronaut-r2dbc
