### ISSUE TITLE
404 by examples link from README

### ISSUE THREAD

**Issue by jreznot** [micronaut-projects/micronaut-reactor#19]
### Task List

- [X] Steps to reproduce provided
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Open README on Github
2. Click on examples link in the sentence:

> Examples can be found in the examples directory.

### Actual Behaviour

404 page shown for https://github.com/micronaut-projects/micronaut-reactor/tree/master/examples

**Comment by sdelamo** [comment]
Thanks for reporting the issue. 

There are no examples for this repository. I am going to remove the section from the `README.md` file.
