### ISSUE TITLE
BOM should probably declare reactor version

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-reactor#254]
### Issue description

Currently the BOM doesn't declare which version of reactor to use, meaning that projects which need an implementation dependency on reactor have to figure out themselves.

**Comment by timyates** [comment]
So currently we use `mn.reactor` to grab a version of reactor core

https://github.com/search?q=org%3Amicronaut-projects%20mn.reactor&type=code

This is defined in core here

https://github.com/micronaut-projects/micronaut-core/blob/4.2.x/gradle/libs.versions.toml#L147

Adding it to here as well will probably cause issues, and removing it from core will cause breakage in all our modules the use it currently...

After chatting with @melix , we decided to close this issue, and live with the current situation for now
